language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk

install: true

script:
  - jdk_switcher use openjdk6
  - export RELADOMO_JDK_HOME="$JAVA_HOME"
  - export RELADOMO_TEST_THREADS=1
  - build/build.sh compile-reladomo-test compile-reladomo-xa-test reladomo-test-suite
  - cat reladomo/target/testresult/TEST-*.xml

branches:
  only:
  - runtests
  - master

git:
  depth: 3

cache:
  directories:
  - lib
  - build/lib

