language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk

install: true

script:
  - jdk_switcher use openjdk6
  - export RELADOMO_JDK_HOME="$JAVA_HOME"
  - export RELADOMO_TEST_THREADS=1
  - build/build.sh reladomo-test-suite l

branches:
  only:
  - runtests2

git:
  depth: 3

cache:
  directories:
  - lib
  - build/lib

